version: "3.8"
services:
  db:
    container_name: anbax-db
    restart: always
    build:
      context: ./db
    env_file: 
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db-network

  server:
    container_name: anbax-server
    build:
      context: ./server
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - db-network
      - client-network
  client:
    container_name: anbax-client
    build:
      context: ./client
    depends_on: 
      - server
    volumes:
      # - /app/node_modules
      - ./client:/usr/src/app
    environment: 
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3001:3001"
    networks: 
      - client-network
networks: 
  db-network: {}
  client-network: {}
volumes:
  db-data: